In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv("cdi grad.csv")


In [3]:
df.head()

otu5      otu8     otu31     otu32     otu63     otu80    otu107  \
0  0.000000  0.048074  0.421139  0.081660  0.000000  0.000000  0.061245   
1  0.010420  0.001226  0.426601  0.081827  0.000000  0.000000  0.460619   
2  0.000000  0.087434  0.063067  0.035834  0.500717  0.080268  0.000000   
3  0.000400  0.123649  0.123249  0.389356  0.020008  0.006803  0.007203   
4  0.003065  0.981332  0.001393  0.000557  0.003901  0.000000  0.000000   

     otu122    otu142    otu145  ...    otu256    otu282    otu308    otu354  \
0  0.001317  0.121831  0.005268  ...  0.043135  0.017781  0.010866  0.010866   
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.012259  0.000000   
2  0.099379  0.035356  0.036312  ...  0.014333  0.000000  0.005733  0.003344   
3  0.108844  0.000000  0.159664  ...  0.024410  0.013205  0.002001  0.002001   
4  0.007523  0.000279  0.000279  ...  0.000000  0.000000  0.000279  0.000000   

     otu425    otu467    otu913  gender         country  Diarrhea  
0  0.000000  0.000000  0.000659       F  TheNetherlands        ND  
1  0.000000  0.000000  0.001532       F  TheNetherlands       AAD  
2  0.002389  0.003822  0.000000       F  TheNetherlands        ND  
3  0.000000  0.000400  0.003601       M  TheNetherlands        ND  
4  0.000000  0.000000  0.000557       M  TheNetherlands        ND  

[5 rows x 25 columns]

In [4]:
df.isnull().sum()

otu5        0
otu8        0
otu31       0
otu32       0
otu63       0
otu80       0
otu107      0
otu122      0
otu142      0
otu145      0
otu156      0
otu162      0
otu166      0
otu188      0
otu189      0
otu256      0
otu282      0
otu308      0
otu354      0
otu425      0
otu467      0
otu913      0
gender      0
country     0
Diarrhea    0
dtype: int64

In [5]:
df["Diarrhea"].value_counts()

ND     669
AAD     64
CDI     14
Name: Diarrhea, dtype: int64

-The numbers mentioned above indicates that the target class is not balanced. So, it is to be balanced in order to get accuracte results.

In [6]:
#encoding Categorical Features:
from sklearn import preprocessing
le= preprocessing.LabelEncoder()
categorical=["country","gender","Diarrhea"]
for c in categorical:
    df[c]=le.fit_transform(df[c])

In [7]:
df.head()

otu5      otu8     otu31     otu32     otu63     otu80    otu107  \
0  0.000000  0.048074  0.421139  0.081660  0.000000  0.000000  0.061245   
1  0.010420  0.001226  0.426601  0.081827  0.000000  0.000000  0.460619   
2  0.000000  0.087434  0.063067  0.035834  0.500717  0.080268  0.000000   
3  0.000400  0.123649  0.123249  0.389356  0.020008  0.006803  0.007203   
4  0.003065  0.981332  0.001393  0.000557  0.003901  0.000000  0.000000   

     otu122    otu142    otu145  ...    otu256    otu282    otu308    otu354  \
0  0.001317  0.121831  0.005268  ...  0.043135  0.017781  0.010866  0.010866   
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.012259  0.000000   
2  0.099379  0.035356  0.036312  ...  0.014333  0.000000  0.005733  0.003344   
3  0.108844  0.000000  0.159664  ...  0.024410  0.013205  0.002001  0.002001   
4  0.007523  0.000279  0.000279  ...  0.000000  0.000000  0.000279  0.000000   

     otu425    otu467    otu913  gender  country  Diarrhea  
0  0.000000  0.000000  0.000659       0        5         2  
1  0.000000  0.000000  0.001532       0        5         0  
2  0.002389  0.003822  0.000000       0        5         2  
3  0.000000  0.000400  0.003601       1        5         2  
4  0.000000  0.000000  0.000557       1        5         2  

[5 rows x 25 columns]

In [8]:
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,roc_auc_score
from sklearn.linear_model import LogisticRegression


In [9]:
target=df["Diarrhea"]
features=df.drop("Diarrhea", axis=1)
features.head()

otu5      otu8     otu31     otu32     otu63     otu80    otu107  \
0  0.000000  0.048074  0.421139  0.081660  0.000000  0.000000  0.061245   
1  0.010420  0.001226  0.426601  0.081827  0.000000  0.000000  0.460619   
2  0.000000  0.087434  0.063067  0.035834  0.500717  0.080268  0.000000   
3  0.000400  0.123649  0.123249  0.389356  0.020008  0.006803  0.007203   
4  0.003065  0.981332  0.001393  0.000557  0.003901  0.000000  0.000000   

     otu122    otu142    otu145  ...    otu189    otu256    otu282    otu308  \
0  0.001317  0.121831  0.005268  ...  0.015476  0.043135  0.017781  0.010866   
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.012259   
2  0.099379  0.035356  0.036312  ...  0.001911  0.014333  0.000000  0.005733   
3  0.108844  0.000000  0.159664  ...  0.000000  0.024410  0.013205  0.002001   
4  0.007523  0.000279  0.000279  ...  0.000000  0.000000  0.000000  0.000279   

     otu354    otu425    otu467    otu913  gender  country  
0  0.010866  0.000000  0.000000  0.000659       0        5  
1  0.000000  0.000000  0.000000  0.001532       0        5  
2  0.003344  0.002389  0.003822  0.000000       0        5  
3  0.002001  0.000000  0.000400  0.003601       1        5  
4  0.000000  0.000000  0.000000  0.000557       1        5  

[5 rows x 24 columns]

In [10]:
#Using Random Forest classifier on Un-balanced data:

def RFModel(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=RandomForestClassifier()
    rf.fit(X_train,y_train)
    y_predict=rf.predict(X_test)
    print(confusion_matrix(y_test,y_predict))
    print(classification_report(y_test,y_predict))
    print("Accuracy score:",accuracy_score(y_test, y_predict))
RFModel(features,target)

[[  0   0  11]
 [  0   0   2]
 [  1   1 135]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.00      0.00      0.00         2
           2       0.91      0.99      0.95       137

    accuracy                           0.90       150
   macro avg       0.30      0.33      0.32       150
weighted avg       0.83      0.90      0.87       150

Accuracy score: 0.9


-The reason behind the inaccurace results is the imbalance in data. 

In [11]:
#Balancing the data using SMOTE technique:
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE().fit_resample(features,target)

In [12]:
def calculate_tpr_fpr(y_test, y_pred):
       
    # Calculates the confusion matrix and recover each element
    cm = confusion_matrix(y_test, y_pred)
    TN = cm[0, 0]
    FP = cm[0, 1]
    FN = cm[1, 0]
    TP = cm[1, 1]
    
    # Calculates tpr and fpr
    tpr =  TP/(TP + FN) # sensitivity - true positive rate
    fpr = 1 - TN/(TN+FP) # 1-specificity - false positive rate
    
    return tpr, fpr

In [13]:
def get_all_roc_coordinates(y_test, y_proba):
    tpr_list = [0]
    fpr_list = [0]
    for i in range(len(y_proba)):
        threshold = y_proba[i]
        y_pred = y_proba >= threshold
        tpr, fpr = calculate_tpr_fpr(y_test, y_pred)
        tpr_list.append(tpr)
        fpr_list.append(fpr)
    return tpr_list, fpr_list

In [14]:
#Getting ROC AUC score using Random forest classifier:

def RFModel_OVR(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=RandomForestClassifier()
    rf.fit(X_train,y_train)
    y_proba=rf.predict_proba(X_test)
    classes=rf.classes_
    roc_auc_ovr = {}
    for i in range(len(classes)):
        c = classes[i]

        # Prepares an auxiliary dataframe to help with the plots
        df_aux = X_test.copy()
        df_aux['class'] = [1 if y == c else 0 for y in y_test]
        df_aux['prob'] = y_proba[:, i]
        df_aux = df_aux.reset_index(drop = True)
        tpr, fpr = get_all_roc_coordinates(df_aux['class'], df_aux['prob'])
        roc_auc_ovr[c] = roc_auc_score(df_aux['class'], df_aux['prob'])
    avg_roc_auc = 0
    i = 0
    for k in roc_auc_ovr:
        avg_roc_auc += roc_auc_ovr[k]
        i += 1
    print(f"average ROC AUC OvR: {avg_roc_auc/i:.4f}")

RFModel_OVR(X_resampled,y_resampled)

average ROC AUC OvR: 0.9959


In [15]:
#Applying Random Forest classifier on balanced data:
def RFModel(X,y):
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=RandomForestClassifier()
    rf.fit(X_train,y_train)
    y_predict=rf.predict(X_test)
    print(confusion_matrix(y_test,y_predict))
    print(classification_report(y_test,y_predict))
    print("Accuracy score:",accuracy_score(y_test, y_predict))
    print("MCC:",metrics.matthews_corrcoef(y_test, y_predict))

RFModel(X_resampled,y_resampled)

[[123   0   6]
 [  0 128   2]
 [  9   4 130]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       129
           1       0.97      0.98      0.98       130
           2       0.94      0.91      0.93       143

    accuracy                           0.95       402
   macro avg       0.95      0.95      0.95       402
weighted avg       0.95      0.95      0.95       402

Accuracy score: 0.9477611940298507
MCC: 0.9217652329786054


In [16]:
#Getting ROC AUC score using Gradient Boosting classifier:

def GBModel_OVR(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=GradientBoostingClassifier()
    rf.fit(X_train,y_train)
    y_proba=rf.predict_proba(X_test)
    classes=rf.classes_
    roc_auc_ovr = {}
    for i in range(len(classes)):
        c = classes[i]

        # Prepares an auxiliar dataframe to help with the plots
        df_aux = X_test.copy()
        df_aux['class'] = [1 if y == c else 0 for y in y_test]
        df_aux['prob'] = y_proba[:, i]
        df_aux = df_aux.reset_index(drop = True)
        tpr, fpr = get_all_roc_coordinates(df_aux['class'], df_aux['prob'])
        roc_auc_ovr[c] = roc_auc_score(df_aux['class'], df_aux['prob'])
    avg_roc_auc = 0
    i = 0
    for k in roc_auc_ovr:
        avg_roc_auc += roc_auc_ovr[k]
        i += 1
    print(f"average ROC AUC OvR: {avg_roc_auc/i:.4f}")

GBModel_OVR(X_resampled,y_resampled)

average ROC AUC OvR: 0.9862


In [17]:
#Applying Gradient Boosting classifier on balanced data:
def GBModel(X,y):
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=GradientBoostingClassifier()
    rf.fit(X_train,y_train)
    y_predict=rf.predict(X_test)
    print(confusion_matrix(y_test,y_predict))
    print(classification_report(y_test,y_predict))
    print("Accuracy score:",accuracy_score(y_test, y_predict))
    print("MCC:",metrics.matthews_corrcoef(y_test, y_predict))

GBModel(X_resampled,y_resampled)

[[121   0   8]
 [  0 130   0]
 [ 17   4 122]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91       129
           1       0.97      1.00      0.98       130
           2       0.94      0.85      0.89       143

    accuracy                           0.93       402
   macro avg       0.93      0.93      0.93       402
weighted avg       0.93      0.93      0.93       402

Accuracy score: 0.927860696517413
MCC: 0.892949111527266


In [18]:
#Applying K_Neareast Neighbor classifier on balanced data:
def kNNModel(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=KNeighborsClassifier()
    rf.fit(X_train,y_train)
    y_predict=rf.predict(X_test)
    print(confusion_matrix(y_test,y_predict))
    print(classification_report(y_test,y_predict))
    print("Accuracy score:",accuracy_score(y_test, y_predict))
    print("MCC:",metrics.matthews_corrcoef(y_test, y_predict))

kNNModel(X_resampled,y_resampled)

[[120   5   4]
 [  0 130   0]
 [ 41  16  86]]
              precision    recall  f1-score   support

           0       0.75      0.93      0.83       129
           1       0.86      1.00      0.93       130
           2       0.96      0.60      0.74       143

    accuracy                           0.84       402
   macro avg       0.85      0.84      0.83       402
weighted avg       0.86      0.84      0.83       402

Accuracy score: 0.835820895522388
MCC: 0.770356057754328
