In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("country.csv")
test=pd.read_csv("test.csv")

In [3]:
df.head()

Otu9     Otu11    Otu34     Otu36     Otu39     Otu66     Otu72  \
0  0.309061  0.000000  0.00000  0.000000  0.000000  0.000000  0.169903   
1  0.003302  0.234043  0.00000  0.000367  0.122157  0.005136  0.013573   
2  0.000000  0.000000  0.00000  0.000000  0.000000  0.000000  0.028169   
3  0.030884  0.000000  0.00852  0.115016  0.009585  0.000000  0.010650   
4  0.183578  0.000000  0.00000  0.063418  0.069426  0.000000  0.000000   

      Otu74     Otu91    Otu100  ...    Otu443    Otu468    Otu501   Otu513  \
0  0.000000  0.000000  0.237864  ...  0.168285  0.000000  0.000000  0.00000   
1  0.002935  0.001834  0.000734  ...  0.001834  0.000000  0.004402  0.01504   
2  0.000000  0.000000  0.281690  ...  0.063380  0.000000  0.000000  0.25000   
3  0.469649  0.000000  0.001065  ...  0.000000  0.008520  0.010650  0.00000   
4  0.007343  0.010013  0.037383  ...  0.000000  0.000668  0.000000  0.00000   

   Otu540    Otu596    Otu603    Otu702   Otu1029           class  
0     0.0  0.000000  0.000000  0.000000  0.114887  TheNetherlands  
1     0.0  0.000000  0.000000  0.021277  0.000734  TheNetherlands  
2     0.0  0.014085  0.000000  0.000000  0.007042  TheNetherlands  
3     0.0  0.002130  0.008520  0.003195  0.002130  TheNetherlands  
4     0.0  0.003338  0.000668  0.000000  0.000668  TheNetherlands  

[5 rows x 41 columns]

In [4]:
df["class"].value_counts()

Spain             307
France            210
Romania           184
Germany           145
Greece             85
TheNetherlands     14
Name: class, dtype: int64

In [5]:
df.isnull().sum()

Otu9       1
Otu11      1
Otu34      1
Otu36      1
Otu39      1
Otu66      1
Otu72      1
Otu74      1
Otu91      1
Otu100     1
Otu134     1
Otu135     1
Otu139     1
Otu145     1
Otu149     1
Otu156     1
Otu188     1
Otu245     1
Otu246     1
Otu256     1
Otu257     1
Otu282     1
Otu292     1
Otu314     1
Otu316     1
Otu318     1
Otu354     1
Otu364     1
Otu370     1
Otu425     1
Otu436     1
Otu443     1
Otu468     1
Otu501     1
Otu513     1
Otu540     1
Otu596     1
Otu603     1
Otu702     1
Otu1029    1
class      0
dtype: int64

In [6]:
df=df.dropna()

In [7]:
from sklearn import preprocessing
le=label_encoder = preprocessing.LabelEncoder()
df["class"]=le.fit_transform(df["class"])

In [8]:
df["class"]

0      5
1      5
2      5
3      5
4      5
      ..
940    0
941    0
942    0
943    0
944    0
Name: class, Length: 944, dtype: int32

In [9]:
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,roc_auc_score
from sklearn.linear_model import LogisticRegression


In [10]:
target=df["class"]
features=df.drop("class", axis=1)
features.head()

Otu9     Otu11    Otu34     Otu36     Otu39     Otu66     Otu72  \
0  0.309061  0.000000  0.00000  0.000000  0.000000  0.000000  0.169903   
1  0.003302  0.234043  0.00000  0.000367  0.122157  0.005136  0.013573   
2  0.000000  0.000000  0.00000  0.000000  0.000000  0.000000  0.028169   
3  0.030884  0.000000  0.00852  0.115016  0.009585  0.000000  0.010650   
4  0.183578  0.000000  0.00000  0.063418  0.069426  0.000000  0.000000   

      Otu74     Otu91    Otu100  ...  Otu436    Otu443    Otu468    Otu501  \
0  0.000000  0.000000  0.237864  ...     0.0  0.168285  0.000000  0.000000   
1  0.002935  0.001834  0.000734  ...     0.0  0.001834  0.000000  0.004402   
2  0.000000  0.000000  0.281690  ...     0.0  0.063380  0.000000  0.000000   
3  0.469649  0.000000  0.001065  ...     0.0  0.000000  0.008520  0.010650   
4  0.007343  0.010013  0.037383  ...     0.0  0.000000  0.000668  0.000000   

    Otu513  Otu540    Otu596    Otu603    Otu702   Otu1029  
0  0.00000     0.0  0.000000  0.000000  0.000000  0.114887  
1  0.01504     0.0  0.000000  0.000000  0.021277  0.000734  
2  0.25000     0.0  0.014085  0.000000  0.000000  0.007042  
3  0.00000     0.0  0.002130  0.008520  0.003195  0.002130  
4  0.00000     0.0  0.003338  0.000668  0.000000  0.000668  

[5 rows x 40 columns]

In [11]:
#Applying Random Forest Classifier on Un_balanced data:

def RFModel(X,y):
    
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=RandomForestClassifier()
    rf.fit(X_train,y_train)
    y_predict=rf.predict(X_test)
    print(confusion_matrix(y_test,y_predict))
    print(classification_report(y_test,y_predict))
    print("Accuracy score:",accuracy_score(y_test, y_predict))
   

RFModel(features,target)

[[12  3  0  8 21  0]
 [ 8  0  0  1 16  0]
 [ 2  0  0  3  7  0]
 [ 0  0  0 26 10  0]
 [ 9  7  0  8 46  0]
 [ 0  1  0  0  1  0]]
              precision    recall  f1-score   support

           0       0.39      0.27      0.32        44
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00        12
           3       0.57      0.72      0.63        36
           4       0.46      0.66      0.54        70
           5       0.00      0.00      0.00         2

    accuracy                           0.44       189
   macro avg       0.23      0.28      0.25       189
weighted avg       0.37      0.44      0.39       189

Accuracy score: 0.4444444444444444


C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


-The numbers generated above are inconsistent.This is because the model only predicted the majority classes.So, the data must be balanced. 

In [12]:
#balancing data using SMOTE anaysis:
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE().fit_resample(features,target)

In [13]:
#Applying Random forest Classifier on balanced data:

RFModel(X_resampled,y_resampled)

[[38  4  2  8 15  0]
 [ 1 52  1  4 10  1]
 [ 2  0 57  1  4  0]
 [ 3  3  2 41  2  0]
 [ 5  9  2  7 34  0]
 [ 0  0  0  0  2 59]]
              precision    recall  f1-score   support

           0       0.78      0.57      0.66        67
           1       0.76      0.75      0.76        69
           2       0.89      0.89      0.89        64
           3       0.67      0.80      0.73        51
           4       0.51      0.60      0.55        57
           5       0.98      0.97      0.98        61

    accuracy                           0.76       369
   macro avg       0.77      0.76      0.76       369
weighted avg       0.77      0.76      0.76       369

Accuracy score: 0.7615176151761518


In [14]:
#Applying Gradient Boosting Classifier on balanced data:
def GBModel(X,y):
    
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=GradientBoostingClassifier()
    rf.fit(X_train,y_train)
    y_predict=rf.predict(X_test)
    print(confusion_matrix(y_test,y_predict))
    print(classification_report(y_test,y_predict))
    print("Accuracy score:",accuracy_score(y_test, y_predict))
    
GBModel(X_resampled,y_resampled)

[[31  4  6  6 17  3]
 [11 41  4  3 10  0]
 [ 1  1 50  7  5  0]
 [ 0  6  1 36  7  1]
 [ 9  6  4  3 33  2]
 [ 0  3  0  0  0 58]]
              precision    recall  f1-score   support

           0       0.60      0.46      0.52        67
           1       0.67      0.59      0.63        69
           2       0.77      0.78      0.78        64
           3       0.65      0.71      0.68        51
           4       0.46      0.58      0.51        57
           5       0.91      0.95      0.93        61

    accuracy                           0.67       369
   macro avg       0.68      0.68      0.67       369
weighted avg       0.68      0.67      0.67       369

Accuracy score: 0.6747967479674797


In [18]:
#Testing the K Nearest Neighbors classifier Model using new data:
def KNNModel(X,y):
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
    rf=KNeighborsClassifier()
    rf.fit(X_train,y_train)
    y_predict=rf.predict(X_test)
    print(confusion_matrix(y_test,y_predict))
    print(classification_report(y_test,y_predict))
    print("Accuracy score:",accuracy_score(y_test, y_predict)) 
KNNModel(X_resampled,y_resampled)

[[30 12  4 15  5  1]
 [12 46  2  3  5  1]
 [ 6  5 43  4  5  1]
 [ 2  7  4 35  2  1]
 [12 13 14  5 10  3]
 [ 0  0  0  0  1 60]]
              precision    recall  f1-score   support

           0       0.48      0.45      0.47        67
           1       0.55      0.67      0.61        69
           2       0.64      0.67      0.66        64
           3       0.56      0.69      0.62        51
           4       0.36      0.18      0.24        57
           5       0.90      0.98      0.94        61

    accuracy                           0.61       369
   macro avg       0.58      0.61      0.59       369
weighted avg       0.58      0.61      0.59       369

Accuracy score: 0.6070460704607046
